# Generated by Django 5.1.6 on 2025-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_useraddedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraddedProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='youStudentID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
