# Generated by Django 5.1.6 on 2025-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='shipping_email',
            field=models.EmailField(default='example@example.com', max_length=300),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='shipping_full_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
